package guitemp;

import javax.swing.*;
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAT190
 */
public class GroupGUI extends JFrame {
    GroupClient gc;
    UserToken token;
    
    String server_host;
    int server_port;
    
    //JFrame parent;
    /**
     * Creates new form GroupGUI
     */
    public GroupGUI() {
        initComponents();
    }
    
    public GroupGUI(UserToken t, String hostname, int port) {
        this();
        
      //  parent = p;
      server_host = hostname;
      server_port = port;
        
        token = t;
        gc = new GroupClient();
        gc.connect(hostname, port);
        
        updateTokenLabel();
        updateGroupList();
        updateUserList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCreateGroup = new JDialog();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        txtCreateGroupName = new JTextField();
        btnCreateGroupCancel = new JButton();
        btnCreateGroupOK = new JButton();
        dlgCreateUser = new JDialog();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        txtCreateUserName = new JTextField();
        btnCreateUserCancel = new JButton();
        bntCreateUserOK = new JButton();
        dlgAddUserToGroup = new JDialog();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        txtAddUserToGroupUser = new JTextField();
        txtAddUserToGroupGroup = new JTextField();
        btnAddUserToGroupCancel = new JButton();
        btnAddUserToGroupOK = new JButton();
        dlgRemoveUserFromGroup = new JDialog();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        txtRemoveUserFromGroupUser = new JTextField();
        txtRemoveUserFromGroupGroup = new JTextField();
        btnRemoveUserFromGroupCancel = new JButton();
        btnRemoveUserFromGroupOK = new JButton();
        dlgDeleteUser = new JDialog();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        txtDeleteUserUser = new JTextField();
        btnDeleteUserCancel = new JButton();
        btnDeleteUserOK = new JButton();
        dlgDeleteGroup = new JDialog();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        txtDeleteGroupGroup = new JTextField();
        btnDeleteGroupCancel = new JButton();
        btnDeleteGroupOK = new JButton();
        jSeparator1 = new JSeparator();
        jPanel2 = new JPanel();
        jScrollPane1 = new JScrollPane();
        groupList = new JList<>();
        jPanel3 = new JPanel();
        jScrollPane2 = new JScrollPane();
        userList = new JList<>();
        jPanel1 = new JPanel();
        lblTokenInfo = new JLabel();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        jLabel17 = new JLabel();
        lblUserName = new JLabel();
        lblIssuer = new JLabel();
        lblGroups = new JLabel();
        lblOwnership = new JLabel();
        jPanel4 = new JPanel();
        btnCreateGroup = new JButton();
        btnDeleteGroup = new JButton();
        btnRemoveFromGroup = new JButton();
        bntAddToGroup = new JButton();
        jSeparator2 = new JSeparator();
        jPanel5 = new JPanel();
        btnCreateUser = new JButton();
        btnDeleteUser = new JButton();
        jSeparator3 = new JSeparator();
        btnDisconnect = new JButton();

        dlgCreateGroup.setTitle("Create Group...");
        dlgCreateGroup.setModal(true);

        jLabel1.setText("Please enter the group to create.");

        jLabel2.setText("Group name:");

        btnCreateGroupCancel.setText("Cancel");
        btnCreateGroupCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupCancelActionPerformed(evt);
            }
        });

        btnCreateGroupOK.setText("OK");
        btnCreateGroupOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupOKActionPerformed(evt);
            }
        });

        GroupLayout dlgCreateGroupLayout = new GroupLayout(dlgCreateGroup.getContentPane());
        dlgCreateGroup.getContentPane().setLayout(dlgCreateGroupLayout);
        dlgCreateGroupLayout.setHorizontalGroup(
            dlgCreateGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCreateGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCreateGroupLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCreateGroupName, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, dlgCreateGroupLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateGroupOK, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateGroupCancel, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dlgCreateGroupLayout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateGroupCancel, btnCreateGroupOK});

        dlgCreateGroupLayout.setVerticalGroup(
            dlgCreateGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCreateGroupName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgCreateGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateGroupCancel)
                    .addComponent(btnCreateGroupOK))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgCreateUser.setTitle("Create User...");
        dlgCreateUser.setModal(true);

        jLabel3.setText("Please enter the user to create.");

        jLabel4.setText("Username:");

        btnCreateUserCancel.setText("Cancel");
        btnCreateUserCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserCancelActionPerformed(evt);
            }
        });

        bntCreateUserOK.setText("OK");
        bntCreateUserOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCreateUserOKActionPerformed(evt);
            }
        });

        GroupLayout dlgCreateUserLayout = new GroupLayout(dlgCreateUser.getContentPane());
        dlgCreateUser.getContentPane().setLayout(dlgCreateUserLayout);
        dlgCreateUserLayout.setHorizontalGroup(
            dlgCreateUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCreateUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCreateUserName))
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, dlgCreateUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntCreateUserOK, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateUserCancel, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dlgCreateUserLayout.setVerticalGroup(
            dlgCreateUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCreateUserName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateUserCancel)
                    .addComponent(bntCreateUserOK))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgAddUserToGroup.setTitle("Add User to Group...");
        dlgAddUserToGroup.setModal(true);

        jLabel5.setText("Please enter the user and group names.");

        jLabel6.setText("Username:");

        jLabel7.setText("Group name:");

        btnAddUserToGroupCancel.setText("Cancel");
        btnAddUserToGroupCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserToGroupCancelActionPerformed(evt);
            }
        });

        btnAddUserToGroupOK.setText("OK");
        btnAddUserToGroupOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserToGroupOKActionPerformed(evt);
            }
        });

        GroupLayout dlgAddUserToGroupLayout = new GroupLayout(dlgAddUserToGroup.getContentPane());
        dlgAddUserToGroup.getContentPane().setLayout(dlgAddUserToGroupLayout);
        dlgAddUserToGroupLayout.setHorizontalGroup(
            dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddUserToGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddUserToGroupLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(dlgAddUserToGroupLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, GroupLayout.Alignment.TRAILING))
                        .addGroup(dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(dlgAddUserToGroupLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtAddUserToGroupGroup))
                            .addGroup(dlgAddUserToGroupLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtAddUserToGroupUser))))
                    .addGroup(GroupLayout.Alignment.TRAILING, dlgAddUserToGroupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddUserToGroupOK, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddUserToGroupCancel, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dlgAddUserToGroupLayout.setVerticalGroup(
            dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddUserToGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddUserToGroupUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddUserToGroupGroup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgAddUserToGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUserToGroupCancel)
                    .addComponent(btnAddUserToGroupOK))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgRemoveUserFromGroup.setTitle("Remove User From Group...");
        dlgRemoveUserFromGroup.setModal(true);

        jLabel8.setText("Please enter the user and group names.");

        jLabel9.setText("Username:");

        jLabel10.setText("Group name:");

        btnRemoveUserFromGroupCancel.setText("Cancel");
        btnRemoveUserFromGroupCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserFromGroupCancelActionPerformed(evt);
            }
        });

        btnRemoveUserFromGroupOK.setText("OK");
        btnRemoveUserFromGroupOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserFromGroupOKActionPerformed(evt);
            }
        });

        GroupLayout dlgRemoveUserFromGroupLayout = new GroupLayout(dlgRemoveUserFromGroup.getContentPane());
        dlgRemoveUserFromGroup.getContentPane().setLayout(dlgRemoveUserFromGroupLayout);
        dlgRemoveUserFromGroupLayout.setHorizontalGroup(
            dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgRemoveUserFromGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dlgRemoveUserFromGroupLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(dlgRemoveUserFromGroupLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtRemoveUserFromGroupUser)
                            .addComponent(txtRemoveUserFromGroupGroup)))
                    .addGroup(GroupLayout.Alignment.TRAILING, dlgRemoveUserFromGroupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemoveUserFromGroupOK, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveUserFromGroupCancel, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        dlgRemoveUserFromGroupLayout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRemoveUserFromGroupCancel, btnRemoveUserFromGroupOK});

        dlgRemoveUserFromGroupLayout.setVerticalGroup(
            dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgRemoveUserFromGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRemoveUserFromGroupUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRemoveUserFromGroupGroup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgRemoveUserFromGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveUserFromGroupCancel)
                    .addComponent(btnRemoveUserFromGroupOK))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgDeleteUser.setTitle("Delete User...");
        dlgDeleteUser.setModal(true);

        jLabel11.setText("Please enter the username.");

        jLabel12.setText("Username:");

        btnDeleteUserCancel.setText("Cancel");
        btnDeleteUserCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserCancelActionPerformed(evt);
            }
        });

        btnDeleteUserOK.setText("OK");
        btnDeleteUserOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserOKActionPerformed(evt);
            }
        });

        GroupLayout dlgDeleteUserLayout = new GroupLayout(dlgDeleteUser.getContentPane());
        dlgDeleteUser.getContentPane().setLayout(dlgDeleteUserLayout);
        dlgDeleteUserLayout.setHorizontalGroup(
            dlgDeleteUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgDeleteUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgDeleteUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDeleteUserLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeleteUserUser))
                    .addGroup(dlgDeleteUserLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, dlgDeleteUserLayout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addComponent(btnDeleteUserOK, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUserCancel, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dlgDeleteUserLayout.setVerticalGroup(
            dlgDeleteUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgDeleteUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgDeleteUserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDeleteUserUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgDeleteUserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteUserCancel)
                    .addComponent(btnDeleteUserOK))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgDeleteGroup.setTitle("Delete Group...");
        dlgDeleteGroup.setModal(true);

        jLabel13.setText("Please enter the group name.");

        jLabel14.setText("Group name:");

        btnDeleteGroupCancel.setText("Cancel");
        btnDeleteGroupCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGroupCancelActionPerformed(evt);
            }
        });

        btnDeleteGroupOK.setText("OK");
        btnDeleteGroupOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGroupOKActionPerformed(evt);
            }
        });

        GroupLayout dlgDeleteGroupLayout = new GroupLayout(dlgDeleteGroup.getContentPane());
        dlgDeleteGroup.getContentPane().setLayout(dlgDeleteGroupLayout);
        dlgDeleteGroupLayout.setHorizontalGroup(
            dlgDeleteGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgDeleteGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgDeleteGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDeleteGroupLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeleteGroupGroup, GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addGroup(dlgDeleteGroupLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, dlgDeleteGroupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteGroupOK, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteGroupCancel, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dlgDeleteGroupLayout.setVerticalGroup(
            dlgDeleteGroupLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dlgDeleteGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgDeleteGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDeleteGroupGroup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgDeleteGroupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteGroupCancel)
                    .addComponent(btnDeleteGroupOK))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Groups");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jSeparator1.setOrientation(SwingConstants.VERTICAL);

        jPanel2.setBorder(BorderFactory.createTitledBorder("Groups"));

        groupList.setModel(new DefaultListModel());
        groupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(groupList);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(BorderFactory.createTitledBorder("Users"));

        userList.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(userList);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel1.setBorder(BorderFactory.createTitledBorder("Token Information"));

        lblTokenInfo.setText("User:");

        jLabel15.setText("Issuer:");

        jLabel16.setText("Groups:");

        jLabel17.setText("Ownership:");

        lblUserName.setText("jLabel18");

        lblIssuer.setText("jLabel19");

        lblGroups.setText("jLabel21");

        lblOwnership.setText("jLabel22");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblTokenInfo, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, GroupLayout.Alignment.TRAILING))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(lblIssuer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGroups, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOwnership, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTokenInfo)
                    .addComponent(lblUserName))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblIssuer))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblGroups))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblOwnership))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCreateGroup.setText("Create Group...");
        btnCreateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupActionPerformed(evt);
            }
        });

        btnDeleteGroup.setText("Delete Group");
        btnDeleteGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGroupActionPerformed(evt);
            }
        });

        btnRemoveFromGroup.setText("Remove User from Group...");
        btnRemoveFromGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromGroupActionPerformed(evt);
            }
        });

        bntAddToGroup.setText("Add User to Group...");
        bntAddToGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddToGroupActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(SwingConstants.VERTICAL);

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateGroup)
                    .addComponent(btnDeleteGroup)
                    .addComponent(bntAddToGroup)
                    .addComponent(btnRemoveFromGroup))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {bntAddToGroup, btnCreateGroup, btnDeleteGroup, btnRemoveFromGroup});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnCreateGroup)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteGroup)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntAddToGroup)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveFromGroup))
            .addComponent(jSeparator2, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        );

        btnCreateUser.setText("Create User...");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete User...");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(btnCreateUser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDeleteUser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnCreateUser)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUser))
        );

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(btnDisconnect, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, GroupLayout.Alignment.LEADING))
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 3, GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDisconnect)
                        .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupActionPerformed
        openCreateGroupDialog();
    }//GEN-LAST:event_btnCreateGroupActionPerformed

    private void groupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupListMouseClicked
        updateUserList();
    }//GEN-LAST:event_groupListMouseClicked

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        gc.disconnect();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void formWindowClosed(WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (gc.isConnected()) gc.disconnect();
 //       parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnCreateGroupCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupCancelActionPerformed
        dlgCreateGroup.setVisible(false);
    }//GEN-LAST:event_btnCreateGroupCancelActionPerformed

    private void btnCreateUserCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserCancelActionPerformed
        dlgCreateUser.setVisible(false);
    }//GEN-LAST:event_btnCreateUserCancelActionPerformed

    private void btnAddUserToGroupCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserToGroupCancelActionPerformed
        dlgAddUserToGroup.setVisible(false);
    }//GEN-LAST:event_btnAddUserToGroupCancelActionPerformed

    private void btnRemoveUserFromGroupCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserFromGroupCancelActionPerformed
        dlgRemoveUserFromGroup.setVisible(false);
    }//GEN-LAST:event_btnRemoveUserFromGroupCancelActionPerformed

    private void btnDeleteUserCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserCancelActionPerformed
        dlgDeleteUser.setVisible(false);
    }//GEN-LAST:event_btnDeleteUserCancelActionPerformed

    private void btnDeleteGroupCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGroupCancelActionPerformed
        dlgDeleteGroup.setVisible(false);
    }//GEN-LAST:event_btnDeleteGroupCancelActionPerformed

    private void bntAddToGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddToGroupActionPerformed
        openAddUserToGroupDialog();
    }//GEN-LAST:event_bntAddToGroupActionPerformed

    private void btnRemoveFromGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromGroupActionPerformed
        openRemoveUserFromGroupDialog();
    }//GEN-LAST:event_btnRemoveFromGroupActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        openCreateUserDialog();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        openDeleteUserDialog();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnDeleteGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGroupActionPerformed
        openDeleteGroupDialog();
    }//GEN-LAST:event_btnDeleteGroupActionPerformed

    private void btnCreateGroupOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupOKActionPerformed
        String g = txtCreateGroupName.getText();
        
        if (!gc.createGroup(g, token)) {
            JOptionPane.showMessageDialog(this, "Unable to create group!");
        }
        
        // Update token.
        reconnect();
        
        updateGroupList();
        updateUserList();
        
        dlgCreateGroup.setVisible(false);
    }//GEN-LAST:event_btnCreateGroupOKActionPerformed

    private void bntCreateUserOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCreateUserOKActionPerformed
        if (!token.getGroups().contains("ADMIN")) {
            JOptionPane.showMessageDialog(this, "Only ADMIN can do that.");
            return;
        }
        
        if (!gc.createUser(txtCreateUserName.getText(), token)) {
            JOptionPane.showMessageDialog(this, "Unable to create user!");
            return;
        }
        
        // ???
        reconnect();
        
        dlgCreateUser.setVisible(false);
    }//GEN-LAST:event_bntCreateUserOKActionPerformed

    private void btnAddUserToGroupOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserToGroupOKActionPerformed
        String u = txtAddUserToGroupUser.getText();
        String g = txtAddUserToGroupGroup.getText();
        
        if (!token.getOwnership().contains(g)) {
            JOptionPane.showMessageDialog(this, "Only the owner can add users.");
            return;
        }
       
        if (!gc.addUserToGroup(u, g, token)) {
            JOptionPane.showMessageDialog(this, "Unable to add user.");
            return;
        }
        
        // Update token (?)
        reconnect();
        
        updateUserList();
        
        dlgAddUserToGroup.setVisible(false);
    }//GEN-LAST:event_btnAddUserToGroupOKActionPerformed

    private void btnRemoveUserFromGroupOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserFromGroupOKActionPerformed
        String u = txtRemoveUserFromGroupUser.getText();
        String g = txtRemoveUserFromGroupGroup.getText();
        
        if (!gc.deleteUserFromGroup(u, g, token)) {
            JOptionPane.showMessageDialog(this, "Unable to remove user from group.");
            return;
        }
        
        // ???
        reconnect();
        
        updateUserList();
        
        dlgRemoveUserFromGroup.setVisible(false);
    }//GEN-LAST:event_btnRemoveUserFromGroupOKActionPerformed

    private void btnDeleteUserOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserOKActionPerformed
        String u = txtDeleteUserUser.getText();
        
        if (!token.getGroups().contains("ADMIN")) {
            JOptionPane.showMessageDialog(this, "Only ADMIN can do that.");
            return;
        }
        
        if (!gc.deleteUser(u, token)) {
            JOptionPane.showMessageDialog(this, "Unable to delete user.");
            return;
        }
        
        // Update token.
        //gc.getToken(token.getSubject());
        reconnect();
        
        updateUserList();
        
        dlgDeleteUser.setVisible(false);
    }//GEN-LAST:event_btnDeleteUserOKActionPerformed

    private void btnDeleteGroupOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGroupOKActionPerformed
        String g = txtDeleteGroupGroup.getText();
        
        if (!token.getOwnership().contains(g)) {
            JOptionPane.showMessageDialog(this, "Only the owner can delete the group");
            return;
        }
        
        if (!gc.deleteGroup(g, token)) {
            JOptionPane.showMessageDialog(this, "Unable to delete group.");
            return;
        }
        
        reconnect();
        
        updateGroupList();
        updateUserList();
        
        dlgDeleteGroup.setVisible(false);
    }//GEN-LAST:event_btnDeleteGroupOKActionPerformed

    
    public void openCreateGroupDialog() {
        txtCreateGroupName.setText("");
        dlgCreateGroup.pack();
        dlgCreateGroup.setVisible(true);
    }
    
    public void openCreateUserDialog() {
        txtCreateUserName.setText("");
        dlgCreateUser.pack();
        dlgCreateUser.setVisible(true);
    }
    
    public void openDeleteGroupDialog() {
        String g = groupList.getSelectedValue();
        
        if (g != null) txtDeleteGroupGroup.setText(g);
        else txtDeleteGroupGroup.setText("");
        dlgDeleteGroup.pack();
        dlgDeleteGroup.setVisible(true);
    }
    
    public void openAddUserToGroupDialog() {
        String g = groupList.getSelectedValue();
        
        if (g != null) txtAddUserToGroupGroup.setText(g);
        else txtAddUserToGroupGroup.setText("");
        
        txtAddUserToGroupUser.setText("");
        dlgAddUserToGroup.pack();
        dlgAddUserToGroup.setVisible(true);
    }
    
    public void openRemoveUserFromGroupDialog() {
        String g = groupList.getSelectedValue();
        String u = userList.getSelectedValue();
        
        if (g != null) txtRemoveUserFromGroupGroup.setText(g);
        else txtRemoveUserFromGroupGroup.setText("");
        
        if (u != null) txtRemoveUserFromGroupUser.setText(u);
        else txtRemoveUserFromGroupUser.setText("");
        
        dlgRemoveUserFromGroup.pack();
        dlgRemoveUserFromGroup.setVisible(true);
    }
    
    public void openDeleteUserDialog() {
        txtDeleteUserUser.setText("");
        dlgDeleteUser.pack();
        dlgDeleteUser.setVisible(true);
    }
    

    
    public void updateTokenLabel() {
        lblUserName.setText(token.getSubject());
        lblIssuer.setText(token.getIssuer());
        lblGroups.setText(token.getGroups().toString());
        lblOwnership.setText(token.getOwnership().toString());
    }
    
    public void updateGroupList() {
        DefaultListModel dlm = (DefaultListModel) groupList.getModel();
        
        dlm.clear();
        for (String s : token.getOwnership())
            dlm.addElement(s);
    }
    
    public void updateUserList() {
        DefaultListModel dlm = (DefaultListModel) userList.getModel();
        String group = groupList.getSelectedValue();

        if (group != null) {
            dlm.clear();
            for (String u : gc.listMembers(group, token))
                dlm.addElement(u);
        }
    }
    
    // Sometimes the client doesn't tell us about changes
    // we make until the next time we connect. I'm sure
    // there's a better way to fix this...
    public void reconnect() {
        gc.disconnect();
        gc.connect(server_host, server_port);
        token = gc.getToken(token.getSubject());
        updateTokenLabel();
    }
    
    public static void go(UserToken t, String hostname, int port) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupGUI(t, hostname, port).setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        go(null, "localhost", 8000);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton bntAddToGroup;
    private JButton bntCreateUserOK;
    private JButton btnAddUserToGroupCancel;
    private JButton btnAddUserToGroupOK;
    private JButton btnCreateGroup;
    private JButton btnCreateGroupCancel;
    private JButton btnCreateGroupOK;
    private JButton btnCreateUser;
    private JButton btnCreateUserCancel;
    private JButton btnDeleteGroup;
    private JButton btnDeleteGroupCancel;
    private JButton btnDeleteGroupOK;
    private JButton btnDeleteUser;
    private JButton btnDeleteUserCancel;
    private JButton btnDeleteUserOK;
    private JButton btnDisconnect;
    private JButton btnRemoveFromGroup;
    private JButton btnRemoveUserFromGroupCancel;
    private JButton btnRemoveUserFromGroupOK;
    private JDialog dlgAddUserToGroup;
    private JDialog dlgCreateGroup;
    private JDialog dlgCreateUser;
    private JDialog dlgDeleteGroup;
    private JDialog dlgDeleteUser;
    private JDialog dlgRemoveUserFromGroup;
    private JList<String> groupList;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JLabel lblGroups;
    private JLabel lblIssuer;
    private JLabel lblOwnership;
    private JLabel lblTokenInfo;
    private JLabel lblUserName;
    private JTextField txtAddUserToGroupGroup;
    private JTextField txtAddUserToGroupUser;
    private JTextField txtCreateGroupName;
    private JTextField txtCreateUserName;
    private JTextField txtDeleteGroupGroup;
    private JTextField txtDeleteUserUser;
    private JTextField txtRemoveUserFromGroupGroup;
    private JTextField txtRemoveUserFromGroupUser;
    private JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
