//package guitemp;
//
//import javax.swing.*;
//
///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//
///**
// *
// * @author Jim
// */
//public class LoginGUI extends JFrame {
//
//    public UserToken token;
//
//    /**
//     * Creates new form LoginGUI
//     */
//    public LoginGUI(/*java.awt.Frame parent, boolean modal*/) {
////        super(parent, modal);
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jScrollPane1 = new JScrollPane();
//        jTextArea1 = new JTextArea();
//        jLabel1 = new JLabel();
//        txtUsername = new JTextField();
//        btnLogin = new JButton();
//        btnGroup = new JButton();
//        btnFile = new JButton();
//        lblStatus = new JLabel();
//        jLabel2 = new JLabel();
//        jLabel3 = new JLabel();
//        txtGroupPort = new JTextField();
//        txtFilePort = new JTextField();
//        jLabel4 = new JLabel();
//        jLabel5 = new JLabel();
//        txtGroupServer = new JTextField();
//        txtFileServer = new JTextField();
//
//        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
//        jScrollPane1.setViewportView(jTextArea1);
//
//        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
//        setTitle("Login");
//
//        jLabel1.setText("Username:");
//
//        btnLogin.setText("Login");
//        btnLogin.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnLoginActionPerformed(evt);
//            }
//        });
//
//        btnGroup.setText("Group Server");
//        btnGroup.setEnabled(false);
//        btnGroup.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnGroupActionPerformed(evt);
//            }
//        });
//
//        btnFile.setText("File Server");
//        btnFile.setEnabled(false);
//        btnFile.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnFileActionPerformed(evt);
//            }
//        });
//
//        lblStatus.setText("Hello ");
//
//        jLabel2.setText("Group Server:");
//
//        jLabel3.setText("File Server:");
//
//        txtGroupPort.setText("8000");
//
//        txtFilePort.setText("8001");
//
//        jLabel4.setText("Port:");
//
//        jLabel5.setText("Port:");
//
//        txtGroupServer.setText("localhost");
//
//        txtFileServer.setText("localhost");
//
//        GroupLayout layout = new GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(10, 10, 10)
//                        .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 346, GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 0, Short.MAX_VALUE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(jLabel1)
//                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, 282, GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                    .addComponent(jLabel2, GroupLayout.Alignment.TRAILING)
//                                    .addComponent(jLabel3, GroupLayout.Alignment.TRAILING))
//                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                    .addComponent(txtFileServer)
//                                    .addComponent(txtGroupServer))
//                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                    .addComponent(jLabel4, GroupLayout.Alignment.TRAILING)
//                                    .addComponent(jLabel5, GroupLayout.Alignment.TRAILING))
//                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
//                                    .addComponent(txtGroupPort, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
//                                    .addComponent(txtFilePort)))
//                            .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                    .addGroup(layout.createSequentialGroup()
//                                        .addComponent(btnGroup, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
//                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
//                                        .addComponent(btnFile, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
//                                    .addComponent(lblStatus))
//                                .addGap(0, 0, Short.MAX_VALUE)))))
//                .addContainerGap())
//        );
//
//        layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFile, btnGroup});
//
//        layout.setVerticalGroup(
//            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel2)
//                    .addComponent(txtGroupPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel4)
//                    .addComponent(txtGroupServer, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel3)
//                    .addComponent(txtFilePort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel5)
//                    .addComponent(txtFileServer, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel1)
//                    .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(btnLogin)
//                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnGroup)
//                    .addComponent(btnFile))
//                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(lblStatus)
//                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
//        if (txtUsername.getText().equals("") ||
//            txtGroupServer.getText().equals("") ||
//            !txtGroupPort.getText().matches("[0-9]{1,4}")) {
//            JOptionPane.showMessageDialog(this, "Invalid username, group server, or port.");
//            return;
//        }
//
//        GroupClient gc = new GroupClient();
//        gc.connect(txtGroupServer.getText(), Integer.parseInt(txtGroupPort.getText()));
//        token = gc.getToken(txtUsername.getText());
//        gc.disconnect();
//
//        if (token == null) {
//            lblStatus.setText("Could not obtain token.");
//            btnGroup.setEnabled(false);
//            btnFile.setEnabled(false);
//        }
//        else {
//            lblStatus.setText("Successfully obtained token.");
//            btnGroup.setEnabled(true);
//            btnFile.setEnabled(true);
//        }
//    }//GEN-LAST:event_btnLoginActionPerformed
//
//    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
//
//        if (txtFileServer.getText().equals("") ||
//            !txtFilePort.getText().matches("[0-9]{1,4}")) {
//            JOptionPane.showMessageDialog(this, "Invalid file server or port.");
//            return;
//        }
//
//        FileGUI.go(token, txtFileServer.getText(), Integer.parseInt(txtFilePort.getText()));
//        this.setVisible(false);
//        dispose();
//    }//GEN-LAST:event_btnFileActionPerformed
//
//    private void btnGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupActionPerformed
//        //dispose();
//        if (txtGroupServer.getText().equals("") ||
//            !txtGroupPort.getText().matches("[0-9]{1,4}")) {
//            JOptionPane.showMessageDialog(this, "Invalid group server or port.");
//            return;
//        }
//        GroupGUI.go(token, txtGroupServer.getText(), Integer.parseInt(txtGroupPort.getText()));
//        this.setVisible(false);
//        dispose();
//    }//GEN-LAST:event_btnGroupActionPerformed
//
//
//    public static void go() {
//         /* Create and display the dialog */
//
//                 /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginGUI().setVisible(true);
//            }
//        });
//    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//       go();
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private JButton btnFile;
//    private JButton btnGroup;
//    private JButton btnLogin;
//    private JLabel jLabel1;
//    private JLabel jLabel2;
//    private JLabel jLabel3;
//    private JLabel jLabel4;
//    private JLabel jLabel5;
//    private JScrollPane jScrollPane1;
//    private JTextArea jTextArea1;
//    private JLabel lblStatus;
//    private JTextField txtFilePort;
//    private JTextField txtFileServer;
//    private JTextField txtGroupPort;
//    private JTextField txtGroupServer;
//    private JTextField txtUsername;
//    // End of variables declaration//GEN-END:variables
//}
