import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jim
 */
public class FileGUI extends javax.swing.JFrame {
    File localdir;
    FileClient fc;
    UserToken token;

    //JFrame parent;
    
    /**
     * Creates new form FileGUI
     */
    public FileGUI() {
        initComponents();
    }
    
    public FileGUI(UserToken t, String hostname, int port) {
        this();
        
        //parent = p;
        
        token = t;
        localdir = new File(".");
        fc = new FileClient();
        fc.connect(hostname, port);
        
        updateLocalList();
        updateRemoteList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        localMenu = new javax.swing.JPopupMenu();
        cmdUpload = new javax.swing.JMenuItem();
        remoteMenu = new javax.swing.JPopupMenu();
        cmdDownload = new javax.swing.JMenuItem();
        cmdRemoteDelete = new javax.swing.JMenuItem();
        dlgUploadPrompt = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUploadLocal = new javax.swing.JTextField();
        txtUploadRemote = new javax.swing.JTextField();
        txtUploadGroup = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnUploadOK = new javax.swing.JButton();
        btnUploadCancel = new javax.swing.JButton();
        dlgDownloadPrompt = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDownloadRemote = new javax.swing.JTextField();
        txtDownloadLocal = new javax.swing.JTextField();
        btnDownloadCancel = new javax.swing.JButton();
        btnDownloadOK = new javax.swing.JButton();
        dlgDeletePrompt = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDeleteRemote = new javax.swing.JTextField();
        btnDeleteCancel = new javax.swing.JButton();
        btnDeleteOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        localPathField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        localList = new javax.swing.JList<>();
        localBrowse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        remotePathField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        remoteList = new javax.swing.JList<>();
        btnUpload = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        btnRemoteDelete = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        cmdUpload.setText("Upload");
        cmdUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUploadActionPerformed(evt);
            }
        });
        localMenu.add(cmdUpload);

        cmdDownload.setText("Download");
        cmdDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDownloadActionPerformed(evt);
            }
        });
        remoteMenu.add(cmdDownload);

        cmdRemoteDelete.setText("Delete");
        cmdRemoteDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRemoteDeleteActionPerformed(evt);
            }
        });
        remoteMenu.add(cmdRemoteDelete);

        dlgUploadPrompt.setTitle("Upload file...");
        dlgUploadPrompt.setAlwaysOnTop(true);
        dlgUploadPrompt.setResizable(false);
        dlgUploadPrompt.setSize(getPreferredSize());

        jLabel1.setText("Local file:");

        jLabel2.setText("Remote file:");

        jLabel3.setText("Group:");

        jLabel4.setText("Please enter the file to upload.");

        btnUploadOK.setText("OK");
        btnUploadOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadOKActionPerformed(evt);
            }
        });

        btnUploadCancel.setText("Cancel");
        btnUploadCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgUploadPromptLayout = new javax.swing.GroupLayout(dlgUploadPrompt.getContentPane());
        dlgUploadPrompt.getContentPane().setLayout(dlgUploadPromptLayout);
        dlgUploadPromptLayout.setHorizontalGroup(
            dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgUploadPromptLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(dlgUploadPromptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgUploadPromptLayout.createSequentialGroup()
                        .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUploadGroup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUploadRemote, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUploadLocal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgUploadPromptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUploadOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUploadCancel)))
                .addContainerGap())
        );

        dlgUploadPromptLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnUploadCancel, btnUploadOK});

        dlgUploadPromptLayout.setVerticalGroup(
            dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgUploadPromptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUploadLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUploadRemote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUploadGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgUploadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadCancel)
                    .addComponent(btnUploadOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgDownloadPrompt.setTitle("Download file...");
        dlgDownloadPrompt.setResizable(false);
        dlgDownloadPrompt.setSize(getPreferredSize());

        jLabel5.setText("Please enter the file to download.");

        jLabel6.setText("Remote file:");

        jLabel7.setText("Local file:");

        btnDownloadCancel.setText("Cancel");
        btnDownloadCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadCancelActionPerformed(evt);
            }
        });

        btnDownloadOK.setText("OK");
        btnDownloadOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgDownloadPromptLayout = new javax.swing.GroupLayout(dlgDownloadPrompt.getContentPane());
        dlgDownloadPrompt.getContentPane().setLayout(dlgDownloadPromptLayout);
        dlgDownloadPromptLayout.setHorizontalGroup(
            dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDownloadPromptLayout.createSequentialGroup()
                .addGroup(dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDownloadPromptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDownloadRemote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDownloadLocal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dlgDownloadPromptLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDownloadPromptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDownloadOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownloadCancel)))
                .addContainerGap())
        );

        dlgDownloadPromptLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDownloadLocal, txtDownloadRemote});

        dlgDownloadPromptLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDownloadCancel, btnDownloadOK});

        dlgDownloadPromptLayout.setVerticalGroup(
            dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDownloadPromptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDownloadRemote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDownloadLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgDownloadPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDownloadOK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDownloadCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgDeletePrompt.setTitle("Delete...");
        dlgDeletePrompt.setModal(true);
        dlgDeletePrompt.setResizable(false);
        dlgDeletePrompt.setSize(getPreferredSize());

        jLabel8.setText("Please enter the remote file.");

        jLabel9.setText("Remote file:");

        btnDeleteCancel.setText("Cancel");
        btnDeleteCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCancelActionPerformed(evt);
            }
        });

        btnDeleteOK.setText("OK");
        btnDeleteOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgDeletePromptLayout = new javax.swing.GroupLayout(dlgDeletePrompt.getContentPane());
        dlgDeletePrompt.getContentPane().setLayout(dlgDeletePromptLayout);
        dlgDeletePromptLayout.setHorizontalGroup(
            dlgDeletePromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDeletePromptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgDeletePromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDeletePromptLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addGroup(dlgDeletePromptLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeleteRemote))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDeletePromptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteCancel)))
                .addContainerGap())
        );

        dlgDeletePromptLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteCancel, btnDeleteOK});

        dlgDeletePromptLayout.setVerticalGroup(
            dlgDeletePromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDeletePromptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(dlgDeletePromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDeleteRemote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgDeletePromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteOK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Files");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Local"));

        localPathField.setEditable(false);

        localList.setModel(new DefaultListModel());
        localList.setComponentPopupMenu(localMenu);
        jScrollPane1.setViewportView(localList);

        localBrowse.setText("Browse...");
        localBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(localPathField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(localBrowse)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote"));

        remotePathField.setEditable(false);

        remoteList.setModel(new DefaultListModel());
        remoteList.setComponentPopupMenu(remoteMenu);
        jScrollPane2.setViewportView(remoteList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(remotePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remotePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpload.setText("Upload...");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnDownload.setText("Download...");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnRemoteDelete.setText("Delete...");
        btnRemoteDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoteDeleteActionPerformed(evt);
            }
        });

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDownload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoteDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisconnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisconnect, btnDownload, btnRemoteDelete, btnUpload});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpload)
                        .addComponent(btnDownload)
                        .addComponent(btnRemoteDelete))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDisconnect)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localBrowseActionPerformed
        // Change local directory
        jFileChooser1.showOpenDialog(this);
        localdir = jFileChooser1.getSelectedFile();
        
        updateLocalList();
    }//GEN-LAST:event_localBrowseActionPerformed

    private void cmdUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUploadActionPerformed
        openUploadDlg();
    }//GEN-LAST:event_cmdUploadActionPerformed

    private void cmdDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDownloadActionPerformed
        openDownloadDlg();
    }//GEN-LAST:event_cmdDownloadActionPerformed

    private void cmdRemoteDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRemoteDeleteActionPerformed
        openDeleteDlg();
    }//GEN-LAST:event_cmdRemoteDeleteActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        fc.disconnect();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        openUploadDlg();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnUploadCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadCancelActionPerformed
        dlgUploadPrompt.setVisible(false);
    }//GEN-LAST:event_btnUploadCancelActionPerformed

    private void btnUploadOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadOKActionPerformed
        String src   = localdir.getPath() + '\\' +txtUploadLocal.getText();
        String dest  = txtUploadRemote.getText();
        String group = txtUploadGroup.getText();

        if (src.length() != 0 && dest.length() != 0 && group.length() != 0) {
            if (token.getGroups().contains(group)) {
                fc.upload(src, dest, group, token);
                dlgUploadPrompt.setVisible(false);
                updateRemoteList();
            }
            else
                JOptionPane.showMessageDialog(this, "You are not a member of that group.");
        }
        else
            JOptionPane.showMessageDialog(this, "All fields are required.");
    }//GEN-LAST:event_btnUploadOKActionPerformed

    private void btnDownloadCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadCancelActionPerformed
        dlgDownloadPrompt.setVisible(false);
    }//GEN-LAST:event_btnDownloadCancelActionPerformed

    private void btnDownloadOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadOKActionPerformed
        String src   = txtDownloadRemote.getText();
        String dest  = localdir.getPath() + '\\' +txtDownloadLocal.getText();

        if (src.length() != 0 && dest.length() != 0) {
            fc.download(src, dest, token);
            dlgDownloadPrompt.setVisible(false);
            updateLocalList();
        }
        else
            JOptionPane.showMessageDialog(this, "All fields are required.");
    }//GEN-LAST:event_btnDownloadOKActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        openDownloadDlg();
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnDeleteCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCancelActionPerformed
        
        dlgDeletePrompt.setVisible(false);
    }//GEN-LAST:event_btnDeleteCancelActionPerformed

    private void btnDeleteOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOKActionPerformed
        String src   = txtDeleteRemote.getText();

        if (src.length() != 0) {
            fc.delete(src, token);
            dlgDeletePrompt.setVisible(false);
            updateRemoteList();
        }
        else
            JOptionPane.showMessageDialog(this, "All fields are required.");
    }//GEN-LAST:event_btnDeleteOKActionPerformed

    private void btnRemoteDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoteDeleteActionPerformed
        openDeleteDlg();
    }//GEN-LAST:event_btnRemoteDeleteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (fc.isConnected()) fc.disconnect();
      //  parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    public void openUploadDlg() {
        // Set default entries
        if (localList.getSelectedValue() != null) {
            txtUploadLocal.setText(localList.getSelectedValue());
            txtUploadRemote.setText(localList.getSelectedValue());
       }
        txtUploadGroup.setText(token.getGroups().get(0));
        
        dlgUploadPrompt.pack();
        dlgUploadPrompt.setVisible(true);
    }
    
    public void openDownloadDlg() {
        // Set default entries
        if (remoteList.getSelectedValue() != null) {
            txtDownloadLocal.setText(remoteList.getSelectedValue());
            txtDownloadRemote.setText(remoteList.getSelectedValue());
       }
        
        dlgDownloadPrompt.pack();
        dlgDownloadPrompt.setVisible(true);
    }
    
    public void openDeleteDlg() {
        // Set default entries
        if (remoteList.getSelectedValue() != null) {
            txtDeleteRemote.setText(remoteList.getSelectedValue());
       }
        
        dlgDeletePrompt.pack();
        dlgDeletePrompt.setVisible(true);
    }
    
    public void updateLocalList() {
        DefaultListModel dlm = (DefaultListModel) localList.getModel();
        
        localPathField.setText(localdir.getPath());
        dlm.clear();
        
        for (File f : localdir.listFiles())
            if (f.isFile())
                dlm.addElement(f.getName());
    }
    
    public void updateRemoteList() {
        DefaultListModel dlm = (DefaultListModel) remoteList.getModel();
        
        remotePathField.setText("/"); // We can't change dirs yet
        dlm.clear();
        
        for (String s : fc.listFiles(token))
            dlm.addElement(s.replace("/","")); // Remove prefixed '/'
    }
    
    public static void go(UserToken t, String hostname, int port) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileGUI(t, hostname, port).setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        go(null, "localhost", 8001);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCancel;
    private javax.swing.JButton btnDeleteOK;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnDownloadCancel;
    private javax.swing.JButton btnDownloadOK;
    private javax.swing.JButton btnRemoteDelete;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnUploadCancel;
    private javax.swing.JButton btnUploadOK;
    private javax.swing.JMenuItem cmdDownload;
    private javax.swing.JMenuItem cmdRemoteDelete;
    private javax.swing.JMenuItem cmdUpload;
    private javax.swing.JDialog dlgDeletePrompt;
    private javax.swing.JDialog dlgDownloadPrompt;
    private javax.swing.JDialog dlgUploadPrompt;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton localBrowse;
    private javax.swing.JList<String> localList;
    private javax.swing.JPopupMenu localMenu;
    private javax.swing.JTextField localPathField;
    private javax.swing.JList<String> remoteList;
    private javax.swing.JPopupMenu remoteMenu;
    private javax.swing.JTextField remotePathField;
    private javax.swing.JTextField txtDeleteRemote;
    private javax.swing.JTextField txtDownloadLocal;
    private javax.swing.JTextField txtDownloadRemote;
    private javax.swing.JTextField txtUploadGroup;
    private javax.swing.JTextField txtUploadLocal;
    private javax.swing.JTextField txtUploadRemote;
    // End of variables declaration//GEN-END:variables
}
